services:
  - type: web
    name: recipe-ingredient-list
    env: node
    buildCommand: cd .. && npm install && npm run build && cd backend && npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromEnvVar: MONGO_URI
      - key: JWT_SECRET
        fromEnvVar: JWT_SECRET
